### ISSUE TITLE
Add support for updating priority of entry.

### ISSUE THREAD

**Issue by nermin99** [luciopaiva/heapify#43]
Since I'm trying to implement Dijkstra's algorithm, I want to be able to update the priority of an already existing entry in the queue.

**Comment by luciopaiva** [comment]
This is another feature planned for v1.0. Similar to what I mentioned [here](https://github.com/luciopaiva/heapify/issues/42), this also means a performance penalty since we'd now need to check if the key already exists in the heap before every push, but it's definitely a feature worth adding (otherwise, Dijkstra implementations - which are very common uses of a priority queue - would not be able to use Heapify).

Thanks for your suggestion.

**Comment by luciopaiva** [comment]
Since this is effectively a duplicate of #24, I will close it to unclutter the issues list.
